name: Test GCP Authentication
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test-auth:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: projects/144231203908/locations/global/workloadIdentityPools/githubpoolgcp/providers/githubactions
        service_account: GCPAutoevaluation@astute-fort-470107-d0.iam.gserviceaccount.com
        audience: https://github.com/assesslytica/gcpevals

    - name: Verify authentication
      run: |
        echo "✅ Authentication successful!"
        gcloud auth list
        gcloud config get-value project
