name: Evaluate GCP Dataproc2 (Retail Transaction Analytics)

on:
  workflow_dispatch:
    inputs:
      student_id:
        description: 'Student ID (for table naming)'
        required: true
        type: string

jobs:
  evaluate:
    runs-on: ubuntu-latest
    env:
      STUDENT_ID: ${{ github.event.inputs.student_id }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud (OIDC)
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r evaluator-gcp-dataproc2/requirements.txt

      - name: Run Dataproc2 evaluator
        run: |
          python evaluator-gcp-dataproc2/scripts/evaluate_dataproc2.py

      - name: Upload evaluation log
        uses: actions/upload-artifact@v4
        with:
          name: dataproc2-evaluation-log
          path: dataproc2_evaluation.log
